// Auto-generated by: npx supabase gen types typescript --local > src/types/database.ts
// Re-run after every schema migration

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole =
  | 'customer'
  | 'b2b_customer'
  | 'partner'
  | 'warehouse_staff'
  | 'delivery_agent'
  | 'admin'

export type InventorySource = 'internal' | 'dropship'

export type OrderStatus =
  | 'pending'
  | 'confirmed'
  | 'processing'
  | 'partially_fulfilled'
  | 'fulfilled'
  | 'shipped'
  | 'delivered'
  | 'cancelled'
  | 'refunded'

export type PaymentStatus =
  | 'pending'
  | 'initiated'
  | 'completed'
  | 'failed'
  | 'refunded'

export type PartnerStatus = 'pending' | 'approved' | 'suspended' | 'rejected'

export type FulfillmentStatus =
  | 'pending'
  | 'accepted'
  | 'picking'
  | 'packed'
  | 'dispatched'
  | 'delivered'
  | 'failed'

export type UnitType =
  | 'bag'
  | 'kg'
  | 'tonne'
  | 'm2'
  | 'litre'
  | 'piece'
  | 'roll'
  | 'box'

// Placeholder until `npx supabase gen types typescript --local` is run against a real DB.
// The `& Record<string, unknown>` intersections are required so that each table satisfies
// Supabase's GenericTable constraint (Row/Insert/Update must extend Record<string, unknown>).
// Without them, the client resolves Schema = never and all Insert/Update ops fail to type-check.
type DbEntry<Row, Insert, Update> = {
  Row: Row & Record<string, unknown>
  Insert: Insert & Record<string, unknown>
  Update: Update & Record<string, unknown>
  Relationships: never[]
}

export interface Database {
  public: {
    Tables: {
      users:          DbEntry<UserRow,         UserInsert,         UserUpdate>
      products:       DbEntry<ProductRow,      ProductInsert,      ProductUpdate>
      orders:         DbEntry<OrderRow,        OrderInsert,        OrderUpdate>
      order_items:    DbEntry<OrderItemRow,    OrderItemInsert,    OrderItemUpdate>
      payments:       DbEntry<PaymentRow,      PaymentInsert,      PaymentUpdate>
      payment_events: DbEntry<PaymentEventRow, PaymentEventInsert, PaymentEventUpdate>
      partners:       DbEntry<PartnerRow,      PartnerInsert,      PartnerUpdate>
      categories:     DbEntry<CategoryRow,     CategoryInsert,     CategoryUpdate>
      delivery_zones: DbEntry<DeliveryZoneRow, DeliveryZoneInsert, DeliveryZoneUpdate>
    }
    Views: Record<string, never>
    Functions: {
      create_order_with_items: {
        Args: { p_order: Json; p_items: Json; p_payment: Json }
        Returns: string
      }
    }
    Enums: Record<string, string[]>
    CompositeTypes: Record<string, null>
  }
}

export interface UserRow {
  id: string
  auth_id: string
  email: string
  phone: string | null
  full_name: string
  role: UserRole
  business_name: string | null
  tin_number: string | null
  preferred_lang: 'en' | 'rw'
  avatar_url: string | null
  is_verified: boolean
  deleted_at: string | null
  created_at: string
  updated_at: string
}
export type UserInsert = Omit<UserRow, 'id' | 'created_at' | 'updated_at'>
export type UserUpdate = Partial<UserInsert>

export interface CategoryRow {
  id: string
  parent_id: string | null
  name_en: string
  name_rw: string | null
  slug: string
  icon_url: string | null
  sort_order: number
  is_active: boolean
  created_at: string
  updated_at: string
}
export type CategoryInsert = Omit<CategoryRow, 'id' | 'created_at' | 'updated_at'>
export type CategoryUpdate = Partial<CategoryInsert>

export interface ProductRow {
  id: string
  category_id: string | null
  partner_id: string | null
  source: InventorySource
  name_en: string
  name_rw: string | null
  slug: string
  description_en: string | null
  description_rw: string | null
  brand: string | null
  sku: string | null
  unit_type: UnitType
  unit_label_en: string
  unit_label_rw: string | null
  base_price: number
  sale_price: number | null
  min_order_qty: number
  weight_kg: number | null
  is_heavy_goods: boolean
  is_active: boolean
  is_featured: boolean
  meta_title: string | null
  meta_description: string | null
  deleted_at: string | null
  created_at: string
  updated_at: string
}
export type ProductInsert = Omit<ProductRow, 'id' | 'created_at' | 'updated_at'>
export type ProductUpdate = Partial<ProductInsert>

export interface OrderRow {
  id: string
  order_number: string
  customer_id: string
  shipping_address_id: string | null
  status: OrderStatus
  order_type: 'b2c' | 'b2b' | 'rfq'
  subtotal: number
  discount_amount: number
  delivery_fee: number
  total_amount: number
  promo_code: string | null
  notes: string | null
  is_approved: boolean
  deleted_at: string | null
  created_at: string
  updated_at: string
}
export type OrderInsert = Omit<OrderRow, 'id' | 'created_at' | 'updated_at'>
export type OrderUpdate = Partial<OrderInsert>

export interface OrderItemRow {
  id: string
  order_id: string
  product_id: string
  variant_id: string | null
  source: InventorySource
  partner_id: string | null
  quantity: number
  unit_price: number
  total_price: number
  commission_rate: number | null
  created_at: string
}
export type OrderItemInsert = Omit<OrderItemRow, 'id' | 'created_at'>
export type OrderItemUpdate = Partial<OrderItemInsert>

export interface PaymentRow {
  id: string
  order_id: string
  pawapay_deposit_id: string | null
  amount: number
  currency: string
  phone_number: string
  operator: 'MTN' | 'AIRTEL' | null
  status: PaymentStatus
  failure_reason: string | null
  initiated_at: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}
export type PaymentInsert = Omit<PaymentRow, 'id' | 'created_at' | 'updated_at'>
export type PaymentUpdate = Partial<PaymentInsert>

export interface PartnerRow {
  id: string
  user_id: string
  business_name: string
  slug: string
  logo_url: string | null
  description: string | null
  tin_number: string | null
  phone: string | null
  email: string | null
  district: string | null
  address: string | null
  commission_rate: number
  status: PartnerStatus
  payout_phone: string | null
  deleted_at: string | null
  created_at: string
  updated_at: string
}
export type PartnerInsert = Omit<PartnerRow, 'id' | 'created_at' | 'updated_at'>
export type PartnerUpdate = Partial<PartnerInsert>

export interface PaymentEventRow {
  id: string
  payment_id: string | null
  event_type: string
  raw_payload: Json
  received_at: string
}
export type PaymentEventInsert = Omit<PaymentEventRow, 'id' | 'received_at'>
export type PaymentEventUpdate = Partial<PaymentEventInsert>

export interface DeliveryZoneRow {
  id: string
  name: string
  districts: string[]
  delivery_fee: number
  min_days: number
  max_days: number
  supports_heavy: boolean
  is_active: boolean
  created_at: string
  updated_at: string
}
export type DeliveryZoneInsert = Omit<DeliveryZoneRow, 'id' | 'created_at' | 'updated_at'>
export type DeliveryZoneUpdate = Partial<DeliveryZoneInsert>
